name: fludgetplanner
description: Flutter app for the Budgetplanner.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^3.2.4
  firebase_core: ^0.2.5
  firebase_analytics: ^1.0.4
  firebase_auth: 0.6.6

  http: ^0.12.0+1
  intl: ^0.15.8

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
